language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rickopsourced/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rickopsourced/react-test npm test

after_sucess:
 - docker build -t rickopsourced/multi-client ./client
 - docker build -t rickopsourced/multi-nginx ./nginx
 - docker build -t rickopsourced/multi-server ./server
 - docker build -t rickopsourced/multi-worker ./worker
#Log into the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push images to docker hub
 - docker push rickopsourced/multi-client
 - docker push rickopsourced/multi-nginx
 - docker push rickopsourced/multi-server
 - docker push rickopsourced/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-244744701857'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
